#!/bin/sh

# copy Monaco scripts and resources
cp -r ./node_modules/monaco-editor/min/vs ./help.pub/js/vs/
cp -r ./node_modules/monaco-editor/min-maps ./help.pub/
cp -r ./node_modules/monaco-themes/themes/ ./playground.mod/lib/

